# Generated by Django 5.2.2 on 2025-06-23 12:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forum', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Category title')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('questions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, editable=False, verbose_name='Is accepted'),
        ),
        migrations.AddField(
            model_name='statelike',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User instance'),
        ),
        migrations.AddField(
            model_name='statelike',
            name='content_type',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(models.Q(('app_label', 'forum'), ('model', 'question')), models.Q(('app_label', 'forum'), ('model', 'answer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model instance reference'),
        ),
        migrations.AddField(
            model_name='statelike',
            name='object_id',
            field=models.PositiveIntegerField(default=None, verbose_name='Real instance ID'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(related_name='questions', to='forum.category', verbose_name='Question categories'),
        ),
    ]
