# Generated by Django 5.2.2 on 2025-06-23 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forum', '0003_category_alter_question_managers_answer_is_accepted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User instance'),
        ),
        migrations.AlterField(
            model_name='statelike',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'forum'), ('model', 'question')), models.Q(('app_label', 'forum'), ('model', 'answer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model instance reference'),
        ),
        migrations.AlterField(
            model_name='statelike',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Real instance ID'),
        ),
    ]
