# Generated by Django 5.2.2 on 2025-06-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('language_code', models.IntegerField(choices=[(1, 'Russian'), (2, 'English'), (3, 'German'), (4, 'Italian'), (5, 'Spanish'), (6, 'Arabic'), (7, 'Dutch'), (8, 'Korean'), (9, 'Chinese'), (10, 'Japanese'), (11, 'Portugal'), (12, 'Latin')], verbose_name='Language ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted at')),
                ('last_upd', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('proficiency_lvl', models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A2+'), (4, 'B1'), (5, 'B1+'), (6, 'B2'), (7, 'B2+'), (8, 'C1'), (9, 'C1+'), (10, 'C2')], verbose_name='Proficiency level ID')),
                ('suggested_lvl', models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A2+'), (4, 'B1'), (5, 'B1+'), (6, 'B2'), (7, 'B2+'), (8, 'C1'), (9, 'C1+'), (10, 'C2')], default=None, null=True, verbose_name='AI-suggested proficiency level ID')),
                ('work_type', models.IntegerField(choices=[(1, 'Prose'), (2, 'Poetry')], verbose_name='Work type (prose/poetry)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Real instance ID')),
                ('comment_text', models.TextField(verbose_name='Comment content')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted at')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Real instance ID')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('language_code', models.IntegerField(choices=[(1, 'Russian'), (2, 'English'), (3, 'German'), (4, 'Italian'), (5, 'Spanish'), (6, 'Arabic'), (7, 'Dutch'), (8, 'Korean'), (9, 'Chinese'), (10, 'Japanese'), (11, 'Portugal'), (12, 'Latin')], verbose_name='Language ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted at')),
                ('last_upd', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('proficiency_lvl', models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A2+'), (4, 'B1'), (5, 'B1+'), (6, 'B2'), (7, 'B2+'), (8, 'C1'), (9, 'C1+'), (10, 'C2')], verbose_name='Proficiency level ID')),
                ('suggested_lvl', models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A2+'), (4, 'B1'), (5, 'B1+'), (6, 'B2'), (7, 'B2+'), (8, 'C1'), (9, 'C1+'), (10, 'C2')], default=None, null=True, verbose_name='AI-suggested proficiency level ID')),
                ('is_rhymed', models.BooleanField(null=True, verbose_name='Poetic translation (for poems only)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslationRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_text', models.CharField(max_length=250, verbose_name='Remark content')),
                ('digit_start', models.IntegerField(verbose_name='Start digit')),
                ('digit_end', models.IntegerField(verbose_name='End digit')),
            ],
        ),
    ]
