# Generated by Django 5.2.2 on 2025-06-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('translations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='originaltext',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='User instance'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='answer_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='translations.postcomment', verbose_name='Answer to comment instance'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User instance'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contenttypes.contenttype', verbose_name='Model instance reference'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User instance'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contenttypes.contenttype', verbose_name='Model instance reference'),
        ),
        migrations.AddField(
            model_name='translation',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.originaltext', verbose_name='Original text instance'),
        ),
        migrations.AddField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='User instance'),
        ),
        migrations.AddField(
            model_name='translationremark',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.translation', verbose_name='Translation instance'),
        ),
    ]
