# Generated by Django 5.2.2 on 2025-06-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='answer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translations.postcomment', verbose_name='Answer to comment instance'),
        ),
    ]
