# Generated by Django 5.2.2 on 2025-06-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_alter_postcomment_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='is_rhymed',
            field=models.BooleanField(default=None, null=True, verbose_name='Poetic translation (for poems only)'),
        ),
    ]
