# Generated by Django 5.2.2 on 2025-06-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_alter_translation_is_rhymed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Slug')),
                ('pattern', models.IntegerField()),
            ],
        ),
    ]
